name: CI

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    container:
      image: docker:latest
      options: --privileged

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Build React Test Image
        run: docker build -t nb1333/react-test -f ./client/Dockerfile.dev ./client

      - name: Run Tests
        run: docker run -e CI=true nb1333/react-test npm test

      - name: Build Docker Images
        run: |
          docker build -t nb1333/multi-client ./client
          docker build -t nb1333/multi-nginx ./nginx
          docker build -t nb1333/multi-server ./server
          docker build -t nb1333/multi-worker ./worker

      - name: Login to Docker Hub
        run: docker login -u ${{ secrets.DOCKER_ID }} -p ${{ secrets.DOCKER_PASSWORD }}

      - name: Push Docker Images
        run: |
          docker push nb1333/multi-client
          docker push nb1333/multi-nginx
          docker push nb1333/multi-server
          docker push nb1333/multi-worker
