name: Multi-docker

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Build and Test
        run: |
          docker build -t nikitabykov/react-test -f ./client/Dockerfile.dev ./client
          docker run -e CI=true nikitabykov/react-test npm test

  deploy:
    runs-on: ubuntu-latest

    needs: build

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Build and Push Docker Images
        run: |
          docker build -t nikitabykov/multi-client ./client
          docker build -t nikitabykov/multi-nginx ./nginx
          docker build -t nikitabykov/multi-server ./server
          docker build -t nikitabykov/multi-worker ./worker

          echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_ID }}" --password-stdin

          docker push nikitabykov/multi-client
          docker push nikitabykov/multi-nginx
          docker push nikitabykov/multi-server
          docker push nikitabykov/multi-worker
